name: Hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world"
      - run: |
          echo "${{ github.run_id}}"
          echo "${{ github.head_ref }}"
          echo "${{ github.workspace }}"
          echo "${{ github.repository }}"
          echo "${{ github.repository_owner }}"
          echo "${{ github.event }}"
          echo "${{ github.actor }}"
      - run: exit 1
      - run: echo "Don't Print"
      - run: echo "いけるか!?"
        if: ${{ failure() }}
